version: '3'
services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./lumen:/var/www
            - ./docker/nginx/log:/var/log/nginx
        ports:
            - "8081:80"
        depends_on:
            - php
    php:
        build:
            context: ./docker/php
        volumes:
            - ./lumen:/var/www
        depends_on:
            - redis
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: lumen
            DB_USERNAME: root
            DB_PASSWORD: root
            REDIS_HOST: redis
    mysql:
        image: mysql:5.7
        volumes:
            - lumen-sample:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=lumen
        ports:
            - "33060:3306"
    redis:
        image: redis:5.0
        ports:
            - "63790:6379"
volumes:
    lumen-sample:
